language: cpp

compiler:
  - gcc

script:
  - cd projects/cmake
  - ./build.sh
  - cd ../..
  - echo "\"Hello World\"" | projects/cmake/rb
  - cd tests
  - ./run_integration_tests.sh

# safelist
branches:
  only:
  - master
  - development
  
# notifications
notifications:
  slack: revbayes:bQO6VTun0Orhx2NiKktVPDsS
