language: cpp

compiler:
  - gcc

script:
# Build
  - cd projects/cmake
  - ./build.sh
# Run tests
  - cd ../..
  - echo "\"Hello World\"" | projects/cmake/rb
  - cd tests
  - ./run_integration_tests.sh
# Run testiphy
  - export PATH=${TRAVIS_BUILD_DIR}/projects/cmake:$PATH
  - cd
  - git clone https://gitlab.com/testiphy/testiphy.git
  - cd testiphy
  - ./testiphy rb

# safelist
branches:
  only:
  - master
  - development
  
# notifications
notifications:
  slack: revbayes:bQO6VTun0Orhx2NiKktVPDsS
